### ISSUE TITLE
As a user, I want to transfer certain amount from another category.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#10]
> As a user, I want to transfer certain amount from another shop list item.

**Tasks**
>Front-end
- [ ] Create an Transfer Items page
- [ ] Create a form that contains
	- [ ] From
	- [ ] Amount to Transfer
- [ ] Add validation
	- [ ] Red color - Wrong, Green color - Correct
	- [ ] Display error message to indicate what the issue is.

>Back-end
- [ ] Field validation.
- [ ] Set error message according to validation
- [ ] Display all category that exist in the system
- [ ] Update information in database

*****
**Priority** : Medium
*****
**Estimate** : 2 days
*****
**Acceptance criteria**

- [ ] Given the allocated amount is less or equal to the selected category, the category's amount can be transferred, else error message is displayed

*****

**Screenshot**
![AddCategory_U_M-1](https://user-images.githubusercontent.com/53347572/154856705-656dadbb-f10b-4b35-bf7e-81b239ffea7f.png)
