### ISSUE TITLE
As a user, I want to add new shop list such that I can allocated amount of money to it (from shop list category).

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#11]
**Tasks**
>Front-end
- [ ] Create an Add Items page
- [ ] Display allocated amount for shop
- [ ] Create a form that contains
	- [ ] Name
	- [ ] Total Cost of Item
	- [ ] Allocated Amount
- [ ] Add validation
	- [ ] Red color - Wrong, Green color - Correct
	- [ ] Display error message to indicate what the issue is.
- [ ] If user selects, "ignore". Procedure to ignore the shop allocation amount limitation and set its priority by default to low.

>Back-end
- [ ] Field validation.
- [ ] Set error message according to validation
- [ ] Display data for Shop Allocated Amount
- [ ] Store information in database
- [ ] If an ignore attribute is present. Do not allocate amount until there is a spot left for it.

*****
**Priority** : Medium
*****
**Estimate** : 3 days
*****
**Acceptance criteria**

- [ ] Given the allocated amount is within shop allocated amount, the shop-list item can be added, else error message is displayed

*****

**Screenshot**
![AddItem_U_M](https://user-images.githubusercontent.com/53347572/154856738-8aae906b-f973-45ed-bb2b-e02e842ac528.png)
