### ISSUE TITLE
As a user, I want to edit shop list such that I can change things accordingly to need.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#12]
**Tasks**
>Front-end
- [ ] Create an Edit Items page
- [ ] Display allocated amount for shop
- [ ] Create a form that contains
	- [ ] Name
	- [ ] Total Cost of Item
	- [ ] Allocated Amount
- [ ] Add validation
	- [ ] Red color - Wrong, Green color - Correct
	- [ ] Display error message to indicate what the issue is.

>Back-end
- [ ] Field validation.
- [ ] Set error message according to validation
- [ ] Display all data that are to be edited
- [ ] Display data for Shop Allocated Amount
- [ ] Store information in database

*****
**Priority** : Medium
*****
**Estimate** : 2 days
*****
**Acceptance criteria**

- [ ] Given the allocated amount is within shop allocated amount, the shop-list item can be edited, else error message is displayed

*****

**Screenshot**
![AddCategory_U_M-1](https://user-images.githubusercontent.com/53347572/154856768-bb5f7969-9591-4093-84a7-1ae83186edc6.png)
