### ISSUE TITLE
As a user, I want to set shop list item priority so that allocation of it will come sooner for it.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#14]
**Tasks**
>  Frontend
 - [ ] Display form.
 - [ ] Add validation of error message and text box highlighting 
	 - [ ] Green for correct, 
	 - [ ] Red for incorrect.
 - [ ] Add flash message to display the action is performed or not. 
 - [ ] Check if the allocated amount is within the shop allocated amount or not. 
	 - [ ] If yes, let user continue. 
	 - [ ] If no, show error stating "the amount has gone over it."

> Backend
 - [ ] If the item listed exceed the shop allocated amount. The allocated amount will be divided according to the priority set.
	 
---

**Form Contains**
 -  Name
 - Total cost of item.
 - Allocated Amount
 -  Priority 

---

**Priority** : Medium

---

**Estimate** : 2 days. 

---

**Acceptance criteria**

 - [ ] Validation.
	 - If wrong, show error message with red highlighting. 
	 - If correct, show green highlighting
 - [ ] Flash message should be shown according to action performed. 
 - [ ] Allocated amount should not exceed the "shop category" allocation amount.

---

**Screenshot**

![AddItem_U_M](https://user-images.githubusercontent.com/53347572/154857015-a9211c4f-7f52-4af0-a115-2d50ed0e8513.png)
