### ISSUE TITLE
As a user, I want to view report of (expense) with items according to the month selected. If not selected, then show the month currently present.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#15]
**Tasks**
>Front-end
- [ ] Create an Report page
- [ ] Add Month Picker
- [ ] Create a list that contains
	- [ ] S.N.
	- [ ] Items
	- [ ] Price
- [ ] Add Total Expense

>Back-end
- [ ] Display data for list/table
- [ ] Add all from price section and display it in Total Expense

*****
**Priority** : Medium
*****
**Estimate** : 2 days
*****

**Screenshot**
![Report_U_M](https://user-images.githubusercontent.com/53347572/154856821-3010d0f1-26c7-4ba7-9e28-5a532c2986b6.png)
