### ISSUE TITLE
As a user, I want to change password.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#16]
**Tasks**
>Front-end
- [ ] Create a Change Password toggle tab
- [ ] Create a form that contains
	- [ ] Old Password
	- [ ] New Password
	- [ ] Confirm Password
- [ ] Add Validation
	- [ ] Red color - Wrong, Green color - Correct
	- [ ] Display error message to indicate what the issue is.
- [ ] Add show/hide password functionality.

>Back-end
- [ ] Field validation.
- [ ] Set error message according to validation.
- [ ] Check inputted old password, with the password stored in database.
- [ ] Check if new and confirm password match
	- [ ] If yes, reset password with the new one. [store in hash]

*****
**Priority** : Medium
*****
**Estimate** : 2 days
*****

**Screenshot**
![Profile-PasswordChange_U_M](https://user-images.githubusercontent.com/53347572/154856834-77076a56-2019-419f-9c14-8ea70fa1950b.png)
