### ISSUE TITLE
As a user, I want to view detail about place where I spent (expenses) and how much i get/have (income)

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#17]
**Tasks**
>  Frontend
 - [ ] Tab UI. 
	 - Expenses
	 - Income
 - [ ] Show list of categories that lies within expenses/income. 
	 - [ ] If present, show the information with the following things. 
		 - Category name
		 - How much overbudget/underbudget it went. 
		 - Total amount spent. 
		 - Total number of transaction. 
	 - [ ] If not present, show an empty state with message, "Oops there is nothing to display". 
 - [ ] Add transaction button.
	 - Dropdown list where user can select either "Expenses" or "Income". 
  - [ ] Sort according to different criteria. 
  - [ ] Show income left and allocated amount for each month.
  - [ ] Add search bar

> Backend
 - [ ] Calculate percentage of category according to total amount allocated. 
 - [ ] Calculate the number of transaction present within that category.
	 - [ ] Once click, show the list of items that are within that category. 
 - [ ] Sort according to latest date of item purchases date. 
 - [ ] Send category list.
 - [ ] Show left amount and allocated amount for selected month. By default, show the current month info. 
 - [ ] Search categories / items.
	 
---

**Tab Contains**
 -  Expenses tab.
	 - Categories name, percentage of underbudget, total amount spent shown in list form, total transaction. 
 -  Income tab.
	 - Categories name, percentage of overbudget, total amount spent shown in list form, total transaction. 
 - Add button 
	 - Add Income
	 - Add Expenses

---

**Priority** : Medium

---

**Estimate** : 3 days. 

---

**Acceptance criteria**

 - [ ] Show list of category if there is data. 
 - [ ] Show empty template if there is no data. 
 - [ ] Drop down should show and let user decide which transaction type to add.
 - [ ] Clicking on the category should show the transaction list. 
 - [ ] Click left or right button on top will show the user data of previous month or next month. 
 - [ ] Badge to indicate what the current status of the expenses is. 
 - [ ] Clicking on month will show the list of month. 
 - [ ] Clicking on the year will show year list. 
 - [ ] Searching will show list of category or items that match with it.

---

**Screenshot**
![Expenses_U_M](https://user-images.githubusercontent.com/53347572/154856919-ad898058-d10f-47c9-abcc-271187a4877f.png)
![Income_U_M](https://user-images.githubusercontent.com/53347572/154856922-a0d6c432-f746-4eda-885e-7349c852979c.png)
