### ISSUE TITLE
As a user, I want to change my personal detail. 

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#18]
**Tasks**
>Front-end
- [ ] Create a Personal Detail toggle tab
- [ ] Create a form that contains
	- [ ] Name
	- [ ] Email
	- [ ] Profile Picture
- [ ] Add Validation
	- [ ] Red color - Wrong, Green color - Correct
	- [ ] Display error message to indicate what the issue is.

>Back-end
- [ ] Field validation.
- [ ] Set error message according to validation.
- [ ] Check photo update size and format.

*****
**Priority** : Medium
*****
**Estimate** : 2 days
*****

**Screenshot**

![Profile_U_M](https://user-images.githubusercontent.com/53347572/154857405-7abd414a-5175-4104-a243-d19f658dcd64.png)
