### ISSUE TITLE
As a user, I want to create new account so that I can use application

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#2]
**Tasks**
>  Frontend
 - [ ] Create signup page. 
 - [ ] Add validation. 
	 - [ ] Red color - Wrong, Green color - Correct
	 - [ ] Display error message to indicate what the issue is. 
 - [ ] Add show/hide password functionality.

> Backend
 - [ ] Field validation. 
 - [ ] Set error message according to validation
 - [ ] Check if email already exist or not? 
	 - [ ] If yes, tell user to do an account recover. 
 - [ ] Add email verification 
 - [ ] Store information in database 
    - [ ] Password should be in hash (crypto package)
---

**Form Contains**
 -  Email.
 - Name.
 - Password
 - Confirm Password. 

---

**Priority** : High 

---

**Estimate** : 2 days. 

---

**Acceptance criteria**

 - [ ] Given the user already has an account when inputting email then it should ask user to do account recovery or notify that an account with the given email id already exist. 
 - [ ] Given the user mistype password when typing confirm password it should then give red indication with error message telling why the error happened. 

---

**Screenshot**

![Register_U_M](https://user-images.githubusercontent.com/53347572/154856270-4ee7af98-17d8-461e-adb0-3ccf9fac8f09.png)
