### ISSUE TITLE
As a user, I want to login into the system.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#3]
> As a user, I want to login into the system.

**Tasks**
>  Frontend
 - [ ] Create login page. 
 - [ ] Add validation. 
	 - [ ] Red color - Wrong, Green color - Correct
	 - [ ] Display error message to indicate what the issue is. 
 - [ ] Add show/hide password functionality.

> Backend
 - [ ] Field validation. 
 - [ ] Set error message according to validation
 - [ ] Check username and password in the system. 
	 - [ ] If present, redirect to dashboard.
	 - [ ] If not present, show error
 - [ ] Check if email is verified. 
	 - [ ] If yes, continue normally. 
	 - [ ] If no, pop-up warning letting user know they need to. 
	 
---

**Form Contains**
 -  Email.
 - Password

---

**Priority** : High 

---

**Estimate** : 3 days. 

---

**Acceptance criteria**

 - [ ] Given user try to login when submitting it check if the user is present in database or not and show error if the user is not present. 
 - [ ] Given goes to dashboard when it logs into the system it should check for email verification, if not warning should show telling user to verify it. 

---

**Screenshot**
![Login_U_M](https://user-images.githubusercontent.com/53347572/154856359-f8bab169-e649-48a2-be9d-e828e2fcde9f.png)
