### ISSUE TITLE
As a user, I want to reset password so that I can recover my account.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#4]
**Tasks**
>  Frontend
 - [ ] Create Forgot Password, Verification Code, Reset password page. 
 - [ ] Add validation. 
	 - [ ] Red color - Wrong, Green color - Correct
	 - [ ] Display error message to indicate what the issue is. 
 - [ ] Add show/hide password functionality.
 - [ ] In verification code page, the keyboard should be number pad of instead of normal. 

> Backend
 - [ ] Field validation. 
 - [ ] Set error message according to validation.
 - [ ] Send verification code to the email. 
 - [ ] Check inputted code, with the code store in database. 
 - [ ] Add resend code button. 
 - [ ] Check email. 
	 - [ ] Reset password with the new one. [store in hash]
	 
---

**Form Contains**
 -  Verification Code Page.
	 - Email. 
 - Verification Code Page. 
	 - 6 digit number input field. 
 - Reset Password Page
	 - New password
	 - Confirm password

---

**Priority** : High 

---

**Estimate** : 3 days. 

---

**Acceptance criteria**

 - [ ] Given I don't remember my password when login then it should ask user to reset password. 
 - [ ] Given I receive code when I submit the forget password form, then email should be sent with the code to be verified. 

---

**Screenshot**
![Forget Password_U_M](https://user-images.githubusercontent.com/53347572/154856447-e57ebc8c-56bf-4659-99b2-8cbc5cec4926.png)
![Verifcation_U_M](https://user-images.githubusercontent.com/53347572/154856455-52d84415-decf-4790-8f8b-eb2e488d663a.png)
![Reset_U_M](https://user-images.githubusercontent.com/53347572/154856459-04421d65-afcf-4c63-9436-591f948774ba.png)
