### ISSUE TITLE
As a user, I want to view list of underbudget, overbudget and cart so that I can perform required action

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#5]
**Tasks**
>  Frontend
 - [ ] Tab UI. 
	 - Underbudget
	 - Overbudget
	 - Cart 
 - [ ] Show list of categories that lies within that tab. 
	 - [ ] If present, show the information with the following things. 
		 - Category name
		 - How much overbudget/underbudget it went. 
		 - Total amount spent. 
	 - [ ] If not present, show an empty state with message, "Oops there is nothing to display". 
 - [ ] Cart Tab should show checklist.
	 - Once checked, it should cross the list names and go to very bottom of the list. 
	 - List should show in the order of priority set. 

> Backend
 - [ ] Calculate percentage of categories that went overbudget/underbudget. 
 - [ ] Send cart list in according of priority set.
	 - [ ] Once checked, it should set status accordingly and go to history logs. 
 - [ ] Click on categories should give all the items present within it. 
 - [ ] Give total income and expenses in the current month. 
 - [ ] Send profile pictures and user's name. 
	 
---

**Tab Contains**
 -  Underbudget tab.
	 - Categories name, percentage of underbudget, total amount spent shown in list form. 
 -  Overbudget tab.
	 - Categories name, percentage of overbudget, total amount spent shown in list form. 
 - Cart tab.
	 - Checklist of items ready to be purchased.

---

**Priority** : Medium

---

**Estimate** : 2 days. 

---

**Acceptance criteria**

 - [ ] Given I am in dashboard when clicking on underbudget it should show list of categories that went underbudget than allocated. 
 - [ ]  Given I am in dashboard when clicking on overbudget it should show list of categories that went overbudget than allocated. 
  - [ ]  Given the user in cart tab when clicking on check on checklist items it should go the bottom and cross the text. 

---

**Screenshot**
![Dashboard_U_M-1](https://user-images.githubusercontent.com/53347572/154856497-6dc162e7-c240-423a-81d1-7ab560d4eb1b.png)
![Dashboard_U_M-2](https://user-images.githubusercontent.com/53347572/154856501-b92c8605-a3ad-4178-a437-7ebc76497f6a.png)
![Dashboard_U_M](https://user-images.githubusercontent.com/53347572/154856507-2ca27bad-b3e5-49df-8ab6-df591b31fa12.png)
