### ISSUE TITLE
As a user, I want to modify/delete transaction such that any mistake might be reverted.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#6]
**Tasks**
>  Frontend
 - [ ] Show Edit and Delete button when slide to the left. 
	 - [ ] If Edit, take to the edit page. 
		 - Show flash card once the action is performed.
	 - [ ] If Delete, open modal that will ask for user confirmation. 
		 - Show flash card once the action is performed.

> Backend
 - [ ] Search for that item ID and edit.
 - [ ] Check for validation of request. 
 - [ ] If delete, perform soft delete and record it in history logs.
 - [ ] Send category options to frontend.

---

**Form Contains**
 -  Name
 - Category (select items) 
 - Amount
 - Date and Time
 
---

**Priority** : Medium

---

**Estimate** : 1 days. 

---

**Acceptance criteria**

 - [ ] Go to edit page and modify. Check for validation. 
 - [ ] Delete should ask for confirmation in case user mistakenly pressed delete. 
 - [ ] It should show flash message according to the action performed by the user. 
 - [ ] It should store performed action in history logs.

---

**Screenshot Reference**

![CategoryList_U_M](https://user-images.githubusercontent.com/53347572/154857158-7efd3c1a-6ede-4abb-ac3b-b4d4c096d6e6.png)
