### ISSUE TITLE
As a user, I want to add new transaction (expenses/income) to keep track of the all transaction.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#7]
**Tasks**
>  Frontend
 - [ ] Display form.
 - [ ] Add validation of error message and text box highlighting 
	 - [ ] Green for correct, 
	 - [ ] Red for incorrect.
 - [ ] Add flash message to display the action is performed or not. 

> Backend
 - [ ] Check for validation, and insert data once done.
	 
---

**Form Contains**
 -  Name
 - Category (select items) 
 - Amount
 - Date and Time

---

**Priority** : Medium

---

**Estimate** : 1 days. 

---

**Acceptance criteria**

 - [ ] Validation.
	 - If wrong, show error message with red highlighting. 
	 - If correct, show green highlighting
 - [ ] Flash message should be shown according to action performed. 
 - [ ] List should be updated.

---

**Screenshot**
![AddTransaction_U_M](https://user-images.githubusercontent.com/53347572/154856576-43428cc6-323f-4d98-9e7e-bad445408940.png)
