### ISSUE TITLE
As a user, I want to add new category such that i can allocated amount of money to it (from total income).

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#8]
**Tasks**
>Front-end
- [ ] Create an Add Category page
- [ ] Display Total amount
- [ ] Create a form that contains
	- [ ] Name
	- [ ] Allocated Amount
	- [ ] Percentage
- [ ] Add validation
	- [ ] Red color - Wrong, Green color - Correct
	- [ ] Display error message to indicate what the issue is.

>Back-end
- [ ] Field validation.
- [ ] Set error message according to validation
- [ ] Display data for Total amount
- [ ] Store information in database

*****
**Priority** : Medium
*****
**Estimate** : 2 days
*****
**Acceptance criteria**

- [ ] Given the allocated amount is within Total amount, the category can be added, else error message is displayed

*****

**Screenshot**
![AddCategory_U_M](https://user-images.githubusercontent.com/53347572/154856679-f07444b7-b0f3-43a0-94df-e5d26c100a7d.png)
