### ISSUE TITLE
As a user, I want to edit cateogry such that i can change things accordingly to need.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/track-life#9]
**Tasks**
>Front-end
- [ ] Create an Edit Category page
- [ ] Display Total amount
- [ ] Create a form that contains
	- [ ] Name
	- [ ] Allocated Amount
	- [ ] Percentage
- [ ] Add validation
	- [ ] Red color - Wrong, Green color - Correct
	- [ ] Display error message to indicate what the issue is.

>Back-end
- [ ] Field validation.
- [ ] Set error message according to validation
- [ ] Display data for Total amount
- [ ] Display all data that are to be edited
- [ ] Store information in database

*****
**Priority** : Medium
*****
**Estimate** : 2 days
*****
**Acceptance criteria**

- [ ] Given the allocated amount is within Total amount, the category can be edited, else error message is displayed

*****

**Screenshot**
![AddCategory_U_M-1](https://user-images.githubusercontent.com/53347572/154856935-768e8d7e-efb2-44d3-83fc-72e1b8cac44e.png)
